#!/bin/sh
################################################################################
# acpi
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting ACPI ...'

    /usr/sbin/acpid -S

    return 0
}

stop() {
    mm_message_output info 'stopping ACPI ...'

    /usr/bin/test -n "`/bin/pidof acpid`" && /usr/bin/killall acpid

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
