#!/bin/sh
################################################################################
# web
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting web server ...'

    # Web page.
    /usr/bin/webfsd -s -u 0 -g 0 -4 -p 80   -j -r /srv/www -x /cgi-bin -f index.html
    # File system.
    /usr/bin/webfsd -s -u 0 -g 0 -4 -p 8080    -r /

    return 0
}


stop() {
    mm_message_output info 'stopping web server ...'

    /usr/bin/test -n "`/bin/pidof webfsd`" && /usr/bin/killall webfsd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
