GARNAME = games
GARVERSION = games
CATEGORIES = games

DESCRIPTION =
define BLURB
endef

DEPENDS    = \
	games/joy2key \
	games/joyevmouse \
	games/crack-attack \
	games/supertux \
	games/neverball \
	games/CriticalMass \
	games/xwelltris \
	games/ri-li

include ../../gar.mk
include ../games.mk

pre-everything: $(INSTALL_DIRS)

