GARNAME      = perl-libwww-perl
GARVERSION   = 5.837
MASTER_SITES = http://www.cpan.org/authors/id/G/GA/GAAS/
DEPENDS      = perl/perl-HTML-Parser perl/perl-URI

include ../../perl/perl/perl-module.mk

CONFIGURE_ARGS += -n

CONFIGURE_ENV := echo N | $(CONFIGURE_ENV)
