#!/bin/sh
/bin/setserial /dev/ttyS1 uart none
modprobe uinput   2>&1 > /dev/null
modprobe lirc_dev   2>&1 > /dev/null
modprobe lirc_serial irq=3 io=0x2f8  2>&1 > /dev/null
mkdir -p /var/run/lirc
lircd --uinput --output=/dev/lircd  2>&1 > /dev/null
