GARNAME = upnp

include ../castorbox/package.api.mk

DEPENDS += \
	testing/mediatomb \
	testing/djmount \
	testing/mediainfo \
	testing/xmlstarlet \


include ../../gar.mk
include ../castorbox/build.api.mk
