BUSYBOX_VERSION = 1.17.2

DEFAULT_ARGS = \
	ARCH="$(GARCH_FAMILY)" \
	HOSTCC="$(build_CC)" \
	HOSTCXX="$(build_CXX)" \
	HOSTCFLAGS="$(build_CFLAGS)" \
	HOSTCXXFLAGS="$(build_CXXFLAGS)" \
	CROSS_COMPILE="$(compiler_prefix)" \
	KBUILD_VERBOSE="1"

CONFIGURE_ARGS = $(DEFAULT_ARGS)
BUILD_ARGS     = $(DEFAULT_ARGS)
INSTALL_ARGS   = $(DEFAULT_ARGS)

CONFIG_PREFIX ?= "$(DESTDIR)$(rootdir)"
