GARNAME = emulators
GARVERSION = emulators
CATEGORIES = emulators

DESCRIPTION =
define BLURB
endef

DEPENDS    = \
	emulators/fceu \
	emulators/zsnes \
	emulators/dgens-sdl \
	emulators/sdlmame \
	emulators/dosbox \
	emulators/mupen64 

include ../../gar.mk

