GARNAME = games

include ../castorbox/package.api.mk

DEPENDS += \
	games/joy2key \
	games/joyevmouse \
	games/crack-attack \
	games/supertux \
	games/neverball \
	games/CriticalMass \
	games/xwelltris \
	games/ri-li

include ../../gar.mk
include ../castorbox/build.api.mk
